# Arreglos y Matrices

Primero importamos las dos librerias.


In [1]:
import numpy as np

## Arreglos: 
Los arreglos de números se hacen con **array** y pueden ser vectores o matrices.

Por ejemplo, mostramos como construir algunos vectores:

In [23]:
v1 = np.array([1,5,10,12]) #vector v1=[1,5,10,12]
v2 = np.array(range(1,31)) #vector cuyas entradas son los números del 1 al 30

Una matriz de tamaño $m\times n$ se crea con **array** de la siguiente forma:

In [2]:
M=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Para extraer elementos de la matriz $M$ se hace los siguiente:

In [3]:
m=2
n=3
print(M[m-1,n-1]) #extrae el elemento M_{23}

8


In [4]:
print(M[1,:]) #Fila 2
print(M[:,3]) #columna 4
print(M[:,-1]) #última columna
print(M[-1,0:-1:2]) #última fina saca elemento desde el primero hasta el último (sin tomarlo) de 2 en 2

[ 6  7  8  9 10]
[ 4  9 14]
[ 5 10 15]
[11 13]


Ahora si tenemos un arreglo en un vector y queremos agrupar dichas entradas en una matriz, usamos la opción **reshape**. Así:

In [25]:
print('v2=',v2)
arreglo = v2.reshape(6,5) #en arreglo organizamos las entradas de v2 en un matriz 6X5
print(arreglo)

v2= [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


### Matrices particulares

In [5]:
Mz=np.zeros((2,5)) #matriz de ceros de tamaño 2X5
print(Mz)
Mo=np.ones((3,3)) #matriz 3X3 llena de unos
print(Mo)
M7=np.full((2,3),7) #matriz 2X3 llena de sietes
print(M7)
Mz23 = np.full(Mz.shape,23) #toma la forma (dimensión) de la matriz Mz y la llena de 23
print(Mz23) 
I5 = np.identity(5) #matriz identidad de tamaño 5X5
print(I5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[23 23 23 23 23]
 [23 23 23 23 23]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Matrices con entradas aleatorias**

In [6]:
Mrand = np.random.rand(4,2) #crea una matriz 4X2 con coeficientes aleatorios entre 0 y 1
print(Mrand)
MrandI = np.random.randint(-4,8, size=(3,3)) # crea una matriz 3X3 aleatoria con enteros entre -4 y 7 (8-1)
print(MrandI)
Mnorm = np.random.normal(0,1,size=(2,2)) # crea una matriz 2X2 aleatoria con distribución normal de media 0 y desviación 1
print(Mnorm)

[[0.42995258 0.57465449]
 [0.90238339 0.55773385]
 [0.377671   0.20284267]
 [0.03342377 0.45711367]]
[[ 6  5  7]
 [ 2 -4 -3]
 [-3  7 -3]]
[[-1.73873668  0.71446136]
 [ 0.17675057 -0.63161849]]


**Arreglos lineales o vectores**

In [7]:
a=2
b=5
n=10
V = np.linspace(a,b,n) #crea un vector fila desde a hasta b (inclusive) dividido en n partes iguales
print(V)

W = np.logspace(a,b,n, base=2) #crea vector fila desde a hasta b en n partes en escala logaritmica de base 2
print(W)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
[ 4.          5.0396842   6.34960421  8.         10.0793684  12.69920842
 16.         20.1587368  25.39841683 32.        ]


**Nota.** Cuando se dese hacer una copia de un array, porque se lo va a modificar, por ejemplo, hacer una copia del vector f en la variable g. No se puede hacer esto:

In [8]:
f=np.linspace(2,3,3)
g=f
g[0]=10
print(f)
print(g)

[10.   2.5  3. ]
[10.   2.5  3. ]


Se debe hacer lo siguiente:

In [9]:
f=np.linspace(2,3,3)
g=f.copy()
g[0]=10
print(f)
print(g)

[2.  2.5 3. ]
[10.   2.5  3. ]


### Operaciones básicas con matrices

Las *operaciones básicas* entre arrays las hace componente a componente:

In [10]:
A=np.array([1,3,5,7])
print('A=',A)
B=np.linspace(7,10,4)
print('B=',B)
print('A+B=',A+B)
print('A*B=',A*B)
print('3*A=',3*A)
print('3+A=',3+A)

A= [1 3 5 7]
B= [ 7.  8.  9. 10.]
A+B= [ 8. 11. 14. 17.]
A*B= [ 7. 24. 45. 70.]
3*A= [ 3  9 15 21]
3+A= [ 4  6  8 10]


Otras operaciones sobre filas o columnas

In [11]:
print(sum(A)) #suma de los elementos de A
print(min(A)) #halla el elemento mínimo de A
print(max(A)) #halla el elemento máximo de A

16
1
7


Para multiplicar dos matrices, se usa *matmul*

In [12]:
M1 = np.random.rand(3,2)
M2 = np.full((2,5),3)
print(np.matmul(M1,M2))

[[2.48166854 2.48166854 2.48166854 2.48166854 2.48166854]
 [3.61629972 3.61629972 3.61629972 3.61629972 3.61629972]
 [3.87036519 3.87036519 3.87036519 3.87036519 3.87036519]]


El *determinante* y la *inversa* de una matriz cuadrada se halla con el paquete **linalg**

In [13]:
import numpy.linalg as npl

In [14]:
N = np.array([[2,-3],[1,0]])
detN = npl.det(N)  #determinante
print(round(detN,5)) 
invN = npl.inv(N) #matriz inversa
print(invN)
NT = npl.matrix_transpose(N) #matriz transpuesta
print(NT)
valsN = npl.eigvals(N) #valores propios
print(valsN)

3.0
[[ 0.          1.        ]
 [-0.33333333  0.66666667]]
[[ 2  1]
 [-3  0]]
[1.+1.41421356j 1.-1.41421356j]
